const fs = require("fs");
const path = require("path");
const fetch = require("node-fetch");

const IG_USER_ID = process.env.IG_USER_ID;
const ACCESS_TOKEN = process.env.IG_ACCESS_TOKEN;
const REPO_RAW_BASE = process.env.REPO_RAW_BASE; // e.g. https://raw.githubusercontent.com/you/repo/main/output
const GRAPH_API = "https://graph.facebook.com/v19.0";

async function createImageContainer(imageUrl) {
  const res = await fetch(
    `${GRAPH_API}/${IG_USER_ID}/media?image_url=${encodeURIComponent(
      imageUrl
    )}&is_carousel_item=true&access_token=${ACCESS_TOKEN}`,
    { method: "POST" }
  );
  const data = await res.json();
  if (!data.id) throw new Error(`Image container failed: ${JSON.stringify(data)}`);
  return data.id;
}

async function createCarouselContainer(childIds, caption) {
  const res = await fetch(
    `${GRAPH_API}/${IG_USER_ID}/media?media_type=CAROUSEL&children=${childIds.join(
      ","
    )}&caption=${encodeURIComponent(caption)}&access_token=${ACCESS_TOKEN}`,
    { method: "POST" }
  );
  const data = await res.json();
  if (!data.id) throw new Error(`Carousel container failed: ${JSON.stringify(data)}`);
  return data.id;
}

async function publish(creationId) {
  const res = await fetch(
    `${GRAPH_API}/${IG_USER_ID}/media_publish?creation_id=${creationId}&access_token=${ACCESS_TOKEN}`,
    { method: "POST" }
  );
  return res.json();
}

async function main() {
  const outputDir = path.join(__dirname, "output");
  if (!fs.existsSync(outputDir)) {
      console.log("No output directory found.");
      return;
  }
  
  const files = fs
    .readdirSync(outputDir)
    .filter((f) => f.endsWith(".png"))
    .sort(); // slide-1.png, slide-2.png, ...

  if (files.length === 0) {
    console.log("No images to post.");
    return;
  }

  const imageUrls = files.map((f) => `${REPO_RAW_BASE}/${f}`);
  console.log("Posting images:", imageUrls);

  const childIds = [];
  for (const url of imageUrls) {
    const id = await createImageContainer(url);
    childIds.push(id);
  }

  // Look for a caption file generated by the pipeline, else use default
  let caption = "Auto-generated post. #automation";
  const captionPath = path.join(outputDir, "caption.txt");
  if (fs.existsSync(captionPath)) {
      caption = fs.readFileSync(captionPath, "utf-8");
  }

  const carouselId = await createCarouselContainer(childIds, caption);
  const result = await publish(carouselId);
  console.log("Published:", result);
}

if (require.main === module) {
    main().catch((err) => {
      console.error(err);
      process.exit(1);
    });
}

module.exports = { main };
